FROM osrf/ros:melodic-desktop-full

ENV CERES_VERSION="1.12.0"

SHELL ["/bin/bash", "-c"]

RUN apt update && apt install libspdlog-dev -y && apt install gdb -y && apt install python3-pip -y
#RUN pip3 install pandas scipy

RUN apt-get update && apt-get install -y \
    cmake \
    libatlas-base-dev \
    libeigen3-dev \
    libgoogle-glog-dev \
    libsuitesparse-dev \
    python-catkin-tools \
    ros-${ROS_DISTRO}-cv-bridge \
    ros-${ROS_DISTRO}-image-transport \
    ros-${ROS_DISTRO}-message-filters \
    ros-${ROS_DISTRO}-tf && \
    rm -rf /var/lib/apt/lists/* && \
    git clone https://ceres-solver.googlesource.com/ceres-solver && \
    cd ceres-solver && \
    git checkout tags/${CERES_VERSION} && \
    mkdir build && cd build && \
    cmake .. && \
    make install && \
    cd ../.. && \
    rm -rf ./ceres-solver

RUN sudo apt install ros-melodic-pcl-ros -y && source opt/ros/melodic/setup.bash 


COPY ../data/a107ac6c-305a-4208-a5a4-b4ef41c68c60/ros-bag/ /ros_bag/

# Create Colcon workspace
RUN mkdir -p /catkin_ws/src


#docker build . --file A-LOAM/docker/Dockerfile_base  -t thesis_aloam